### ISSUE TITLE
Combinations

### ISSUE THREAD

**Issue by sahastrakishore123** [dexterpuru/leetcode_cpp#18]
**Question Link**- https://leetcode.com/problems/combinations/#/description
Given two integers n and k, return all possible combinations of k numbers out of 1 ... n.

You may return the answer in any order.

Example 1:

Input: n = 4, k = 2
Output:
[
  [2,4],
  [3,4],
  [2,3],
  [1,2],
  [1,3],
  [1,4],
]
Example 2:

Input: n = 1, k = 1
Output: [[1]]

Constraints:

1 <= n <= 20
1 <= k <= n

Would you like to do this issue?
Yes, I would like to do this as a part of Hacktoberfest and also label it.

**Comment by sahastrakishore123** [comment]
@dexterpuru Kindly assign me for this issue as I have completed previous two issues.

**Comment by dexterpuru** [comment]
@sahastrakishore123 go ahead 👍
