### ISSUE TITLE
<Add> Permutations LeetCode Solution

### ISSUE THREAD

**Issue by Sahastracookcoder1** [dexterpuru/leetcode_cpp#2]
**Given a collection of distinct integers, return all possible permutations.**
**Difficulty**- Medium 

Example:

Input: [1,2,3]
Output:
[
  [1,2,3],
  [1,3,2],
  [2,1,3],
  [2,3,1],
  [3,1,2],
  [3,2,1]
]

Here's the problem link- https://leetcode.com/problems/permutations/#/description

**Would you like to do this issue?**
Yes, I would like to do this issue and also assign me to do so.

**Comment by Sahastracookcoder1** [comment]
@dexterpuru Kindly assign me to do this issue as a part of Hacktoberfest and also label it.

**Comment by dexterpuru** [comment]
@Sahastracookcoder1 please go ahead and make a PR when ever you are ready

**Comment by dexterpuru** [comment]
@Sahastracookcoder1 Great work so far, i have made some comments in PR please have a look at them.

**Comment by Sahastracookcoder1** [comment]
@dexterpuru  I have updated the code kindly look it into the PR #8

**Comment by dexterpuru** [comment]
Only thing left now is to rename the Question.md file to README.md, the you are good to go.

**Comment by Sahastracookcoder1** [comment]
Okay, fine changing...
