### ISSUE TITLE
First Unique Character in a String

### ISSUE THREAD

**Issue by MohakChugh** [dexterpuru/leetcode_cpp#38]
**Question Link**
https://leetcode.com/problems/first-unique-character-in-a-string/

Given a string, find the first non-repeating character in it and return its index. If it doesn't exist, return -1.

```
Examples:

s = "leetcode"
return 0.

s = "loveleetcode"
return 2.
 ```

Note: You may assume the string contains only lowercase English letters.

**Comment by dexterpuru** [comment]
@MohakChugh go ahead 👍

**Comment by MohakChugh** [comment]
Please review the PR :)
