### ISSUE TITLE
Spiral Matrix

### ISSUE THREAD

**Issue by ritik-gupta** [dexterpuru/leetcode_cpp#4]
https://leetcode.com/problems/spiral-matrix/submissions

**Comment by dexterpuru** [comment]
@ritik-gupta please go ahead and make the PR whenever your work is ready.

Follow these while doing the Work
1. For every question you will have to add a folder, whose name will be Spiral Matrix in your case, and every folder will contain 2 files.
First file is README.md which contains Question Link, Problem Statement with testcases and then the approach you followed to make the solution.
Second File is Solution.cpp, which contains the code.
