### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by HarshTyagi007** [dexterpuru/leetcode_cpp#40]
**Question Link**
https://leetcode.com/problems/letter-combinations-of-a-phone-number/

**Difficulty Level** -- Medium

Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent.

A mapping of digit to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

![image](https://user-images.githubusercontent.com/48311361/94986468-aeb34580-057c-11eb-8610-5716d48e3984.png)

Example:

Input: "23"
Output: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"].
Note:

Although the above answer is in lexicographical order, your answer could be in any order you want.

**Would you like to do this issue?**
Yes, I would love to contribute to this repo kindly assign me this issue with hacktoberfest label.

**Comment by HarshTyagi007** [comment]
@dexterpuru   Assign me this issue with hacktoberfest label.

**Comment by dexterpuru** [comment]
@HarshTyagi007 🟢
