### ISSUE TITLE
Flatten nested list iterator

### ISSUE THREAD

**Issue by ritik-gupta** [dexterpuru/leetcode_cpp#5]
https://leetcode.com/problems/flatten-nested-list-iterator

Given a nested list of integers, implement an iterator to flatten it.

Each element is either an integer, or a list -- whose elements may also be integers or other lists.

Example 1:

Input: [[1,1],2,[1,1]]
Output: [1,1,2,1,1]
Explanation: By calling next repeatedly until hasNext returns false, 
             the order of elements returned by next should be: [1,1,2,1,1].

**Comment by dexterpuru** [comment]
@ritik-gupta great issue format, go ahead!!
