### ISSUE TITLE
Set Matrix Zeroes

### ISSUE THREAD

**Issue by qwerty22121998** [dexterpuru/leetcode_cpp#50]
**Question Link**
https://leetcode.com/problems/set-matrix-zeroes/
Given an m x n matrix. If an element is 0, set its entire row and column to 0. Do it in-place.

**Comment by qwerty22121998** [comment]
@dexterpuru hi, could you please assign this issue for me ?

**Comment by dexterpuru** [comment]
@qwerty22121998 go ahead 👍
